### PR TITLE
Add: Guide to Database Selection + Other Changes

### PR DESCRIPTION
**Pull request by sawhney17**

### CODE REVIEW

**Comment by sawhney17** [comment]
I've fixed a couple of links in the handbook.

**Comment by sawhney17** [comment]
Just Updated the Awesom-Athens page with browser extensions

**Comment by sawhney17** [comment]
Added a few of the text expander workfows, namely Excalidraw integration and the Spaced Repetition System. Will add integration via Expanso shortly.

**Review by jsmorabito — APPROVED** [review]
🙏

**Pull request merged**
